### ISSUE TITLE
Implement Add a cylinder to the Inventory

### ISSUE THREAD

**Issue by pembertonc** [pembertonc/gs.github.io#31]
Add a cylinder to inventory.  The system will prompt the user for, the cylinder type, serial no, capacity and owner of the cylinder.

The system should check that the "serial no" does not already exist in system.

All fields are required.

Add cylinder should have a button to save the completed input to the back end.

Each Cylinder will have a non contextual id generated. 

There should be a cancel button.

See the discussion on color theme or speak to Wayne Bethany, or Clive.

**Comment by pembertonc** [comment]
No need to go outside of the dev environment.  Use github

**Comment by pembertonc** [comment]
Implement the java controller for add cylinder.  Creating the wicket components to match each of the html components.

**Comment by yog-droid** [comment]
updated code pen with css updates:
https://codepen.io/Bcodes21/pen/GREZoBP
