### ISSUE TITLE
AddCylinderPage - InitializeCylinderGasType

### ISSUE THREAD

**Issue by pembertonc** [pembertonc/gs.github.io#44]
Implement method initializeCylinderGasType.

1.  create wicket:id in AddCylinderPage.html for component with id:cylinderGasType;
2.  code method initializeCylinderGasType(), so that an instance of "org.apache.wicket.markup.html.form.DropDownChoice" is created which is bound to the wicket:id="cylinderGasType".
3.  assign the instance created in number 2 to the field instance variable cylinderGasType.  
4.  In the onInitializeMethod of the AddCylinderPage add the cylinderGasType DropDownChoice component to the form by calling form.add(cylinderGasType);

**Comment by darh86** [comment]
I'll do this one
