### ISSUE TITLE
AddCylinderPage - initializeCylinderCapacity

### ISSUE THREAD

**Issue by pembertonc** [pembertonc/gs.github.io#45]
Implement method initializeCylinderCapacity.

1.  create wicket:id in AddCylinderPage.html for component with id:cylinderCapacity;  
2.  code method initializeCylinderCapacity(), so that an instance of "org.apache.wicket.markup.html.form.DropDownChoice" is created which is bound to the wicket:id="cylinderCapacity".  
3. assign the instance created in number 2 to the field instance variable cylinderCapacity.   
4. In the onInitializeMethod of the AddCylinderPage add the cylinderCapacity DropDownChoice component to the form by calling form.add(cylinderCapacity);

**Comment by akiferrol** [comment]
i can try
