### ISSUE TITLE
AddCylinderPage - initializeAdd

### ISSUE THREAD

**Issue by pembertonc** [pembertonc/gs.github.io#47]
Implement method initializeAdd.

1. create wicket:id in AddCylinderPage.html for component with id:add;  
2. code method initializeAdd(), so that an instance of "org.apache.wicket.ajax.markup.html.form.AjaxFallbackButton" is created which is bound to the wicket:id="add".  
3.  assign the instance created in number 2 to the field instance variable add.  
4. In the onInitializeMethod of the AddCylinderPage add the  AjaxFallbackButton component to the form by calling form.add(add);

**Comment by akiferrol** [comment]
I can try this
