### ISSUE TITLE
Login Page Layout

### ISSUE THREAD

**Issue by pembertonc** [pembertonc/gs.github.io#64]
Create the Login page in accordance with the sheared document showing the appearance of pages

**Comment by Chesedah** [comment]
Login page has been pushed to Git Hub. 

1. Page loads fine however The Avatar (company Logo) fails to display.
2. The head tags have an issue. the code is correct however they refuse to connect
3. The body tags are producing the same issue as the head tags.

**Comment by Chesedah** [comment]
Login Page new pull request has been sent and update has just been pushed.

1. Avatar containing Gas Supply Company logo is now displaying.

**Comment by Chesedah** [comment]
Tasks left:

1.Fix issues 2&3 from previous comment and update colour scheme to scheme to match the rest of the website.
2. Sync Login page with Java page.
3. Add Wicket:IDs'
4.  Sync Login page with user security database

**Comment by pembertonc** [comment]
Login page Completed
